Build started 7/21/2015 8:09:52 PM.
     1>Project "C:\Users\Smith\Documents\Python_CPP_cSharp\CPP DLL\PyCallFuncs\PyCallFuncs\PyCallFuncs.vcxproj" on node 3 (Build target(s)).
     1>Link:
         C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\link.exe /ERRORREPORT:PROMPT /OUT:"C:\Users\Smith\Documents\Python_CPP_cSharp\CS console app\ConsoleApplication1\Debug\PyCallFuncs.dll" /INCREMENTAL /NOLOGO /LIBPATH:C:\Users\Smith\Anaconda3\libs kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:\Users\Smith\Documents\Python_CPP_cSharp\CS console app\ConsoleApplication1\Debug\PyCallFuncs.pdb" /SUBSYSTEM:WINDOWS /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:\Users\Smith\Documents\Python_CPP_cSharp\CS console app\ConsoleApplication1\Debug\PyCallFuncs.lib" /MACHINE:X86 /DLL Debug\PyCallFuncs.obj
     1>LINK : fatal error LNK1104: cannot open file 'python34_d.lib'
     1>Done Building Project "C:\Users\Smith\Documents\Python_CPP_cSharp\CPP DLL\PyCallFuncs\PyCallFuncs\PyCallFuncs.vcxproj" (Build target(s)) -- FAILED.

Build FAILED.

Time Elapsed 00:00:00.29
